/**
 * Pass 0 + Pass 1: prescan the repo, then run the scanner agent to produce
 * the feature inventory (inventory.md for the admin, inventory.json for
 * `codedocent write`).
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import type { AgentRuntime, AgentProgress } from '../runtime/types.js';
import { prescan } from './prescan.js';
import { scannerPrompt, type FeatureSpec } from './prompts.js';
import { openWorkspace, loadSkills, repoCommit, logRun, type Workspace } from './workspace.js';

export function extractFenced(text: string, lang: string): string | null {
  const re = new RegExp('```' + lang + '\\s*\\n([\\s\\S]*?)```');
  const m = text.match(re);
  return m ? m[1] : null;
}

/**
 * Find a JSON object containing "features" anywhere in the text, even without a
 * ```json fence (some runtimes return raw JSON or wrap it in prose). Balances
 * braces from the first `{` before the "features" key. Tolerant of a leading
 * gutter (e.g. copilot may box output with "│ " on each line) by stripping a
 * common one-line prefix before parsing.
 */
export function extractJson(text: string): string | null {
  const fenced = extractFenced(text, 'json') ?? extractFenced(text, 'JSON');
  const candidates: string[] = [];
  if (fenced) candidates.push(fenced);

  const key = text.indexOf('"features"');
  if (key >= 0) {
    const start = text.lastIndexOf('{', key);
    if (start >= 0) {
      let depth = 0;
      for (let j = start; j < text.length; j++) {
        if (text[j] === '{') depth++;
        else if (text[j] === '}' && --depth === 0) {
          candidates.push(text.slice(start, j + 1));
          break;
        }
      }
    }
  }

  for (const c of candidates) {
    for (const variant of [c, stripLineGutters(c)]) {
      try {
        const obj = JSON.parse(variant);
        if (obj && Array.isArray(obj.features)) return variant;
      } catch {
        /* try next */
      }
    }
  }
  return null;
}

/** Strip a repeated leading gutter (│, |, >, *) that CLI panels add to each line. */
function stripLineGutters(s: string): string {
  return s
    .split('\n')
    .map((l) => l.replace(/^\s*[│|>*]\s?/, ''))
    .join('\n');
}

export async function runPrescan(project: string, repoDir: string): Promise<string> {
  const ws = openWorkspace(project);
  const report = prescan(repoDir);
  const out = path.join(ws.root, 'prescan.json');
  fs.writeFileSync(out, JSON.stringify(report, null, 2));
  return out;
}

export async function runScan(
  project: string,
  repoDir: string,
  runtime: AgentRuntime,
  model?: string,
  onProgress?: (ev: AgentProgress) => void,
): Promise<{ inventoryPath: string; features: FeatureSpec[] }> {
  const ws = openWorkspace(project);
  const report = prescan(repoDir);
  fs.writeFileSync(path.join(ws.root, 'prescan.json'), JSON.stringify(report, null, 2));

  const commit = await repoCommit(repoDir);
  const prompt = scannerPrompt(report, loadSkills(ws), commit);

  let features: FeatureSpec[] = [];
  try {
    const result = await runtime.run({ role: 'scanner', prompt, repoDir, model, maxTurns: 30, onProgress });
    logRun(ws, 'scanner', 'scan', result);

    const json = extractJson(result.text);
    if (!json) {
      const dump = path.join(ws.root, 'scanner-raw-output.txt');
      fs.writeFileSync(dump, result.text);
      throw new Error(
        `scanner returned no parseable JSON (raw output saved to ${dump}).\n` +
          `First 400 chars of what the model returned:\n${result.text.slice(0, 400)}`,
      );
    }
    features = (JSON.parse(json).features ?? []) as FeatureSpec[];
    if (features.length === 0) throw new Error('scanner returned zero features');

    // Render the human-readable table ourselves from the parsed features — the
    // model outputs JSON only, so it doesn't spend generation time (and idle
    // budget) emitting the same list twice.
    const rows = features
      .map(
        (f) =>
          `| ${f.slug} | ${f.name} | ${(f.entryPoints ?? []).join(', ')} | ${(f.codeAreas ?? []).join(', ')} |`,
      )
      .join('\n');
    const inventoryMd = [
      `# Feature Inventory — ${project}`,
      '',
      `> Generated by runtime \`${runtime.name}\` at commit \`${commit}\` on ${new Date().toISOString().slice(0, 10)}.`,
      '> Review this list (rename, merge, split, exclude), then it drives `codedocent write <slug>`.',
      '',
      `${features.length} features:`,
      '',
      '| slug | feature | entry points | key code areas |',
      '|---|---|---|---|',
      rows,
      '',
    ].join('\n');
    fs.writeFileSync(path.join(ws.root, 'inventory.md'), inventoryMd);
    fs.writeFileSync(path.join(ws.root, 'inventory.json'), JSON.stringify({ commit, features }, null, 2));
  } catch (err) {
    logRun(ws, 'scanner', 'scan', { error: (err as Error).message });
    throw err;
  }

  return { inventoryPath: path.join(ws.root, 'inventory.md'), features };
}

export function loadInventory(ws: Workspace): FeatureSpec[] {
  const file = path.join(ws.root, 'inventory.json');
  if (!fs.existsSync(file)) return [];
  return (JSON.parse(fs.readFileSync(file, 'utf8')).features ?? []) as FeatureSpec[];
}
