/**
 * Pass 0 + Pass 1: prescan the repo, then run the scanner agent to produce
 * the feature inventory (inventory.md for the admin, inventory.json for
 * `codedocent write`).
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import type { AgentRuntime, AgentProgress } from '../runtime/types.js';
import { prescan } from './prescan.js';
import { scannerPrompt, type FeatureSpec } from './prompts.js';
import { openWorkspace, loadSkills, repoCommit, logRun, type Workspace } from './workspace.js';

export function extractFenced(text: string, lang: string): string | null {
  const re = new RegExp('```' + lang + '\\s*\\n([\\s\\S]*?)```');
  const m = text.match(re);
  return m ? m[1] : null;
}

export async function runPrescan(project: string, repoDir: string): Promise<string> {
  const ws = openWorkspace(project);
  const report = prescan(repoDir);
  const out = path.join(ws.root, 'prescan.json');
  fs.writeFileSync(out, JSON.stringify(report, null, 2));
  return out;
}

export async function runScan(
  project: string,
  repoDir: string,
  runtime: AgentRuntime,
  model?: string,
  onProgress?: (ev: AgentProgress) => void,
): Promise<{ inventoryPath: string; features: FeatureSpec[] }> {
  const ws = openWorkspace(project);
  const report = prescan(repoDir);
  fs.writeFileSync(path.join(ws.root, 'prescan.json'), JSON.stringify(report, null, 2));

  const commit = await repoCommit(repoDir);
  const prompt = scannerPrompt(report, loadSkills(ws), commit);

  let features: FeatureSpec[] = [];
  try {
    const result = await runtime.run({ role: 'scanner', prompt, repoDir, model, maxTurns: 30, onProgress });
    logRun(ws, 'scanner', 'scan', result);

    const json = extractFenced(result.text, 'json');
    if (!json) throw new Error('scanner returned no ```json block');
    features = (JSON.parse(json).features ?? []) as FeatureSpec[];
    if (features.length === 0) throw new Error('scanner returned zero features');

    const inventoryMd = [
      `# Feature Inventory — ${project}`,
      '',
      `> Generated by runtime \`${runtime.name}\` at commit \`${commit}\` on ${new Date().toISOString().slice(0, 10)}.`,
      '> Review this list (rename, merge, split, exclude), then it drives `codedocent write <slug>`.',
      '',
      result.text.replace(/```json[\s\S]*?```/, '').trim(),
      '',
    ].join('\n');
    fs.writeFileSync(path.join(ws.root, 'inventory.md'), inventoryMd);
    fs.writeFileSync(path.join(ws.root, 'inventory.json'), JSON.stringify({ commit, features }, null, 2));
  } catch (err) {
    logRun(ws, 'scanner', 'scan', { error: (err as Error).message });
    throw err;
  }

  return { inventoryPath: path.join(ws.root, 'inventory.md'), features };
}

export function loadInventory(ws: Workspace): FeatureSpec[] {
  const file = path.join(ws.root, 'inventory.json');
  if (!fs.existsSync(file)) return [];
  return (JSON.parse(fs.readFileSync(file, 'utf8')).features ?? []) as FeatureSpec[];
}
